# -*- coding: utf-8 -*-
"""Generate reference tokenizer outputs (HF tokenizers Rust) for UnigramTokenizerTest.

Usage: python tools/gen_unigram_reference.py
Reads:  app/src/main/assets/models/tokenizer.json
Writes: app/src/test/java/io/prism/embedding/UnigramTokenizerReference.kt
"""
import json
import pathlib

from tokenizers import Tokenizer

ROOT = pathlib.Path(__file__).resolve().parents[1]
TOKENIZER_JSON = ROOT / "app" / "src" / "main" / "assets" / "models" / "tokenizer.json"
OUT_KT = ROOT / "app" / "src" / "test" / "java" / "io" / "prism" / "embedding" / "UnigramTokenizerReference.kt"

tok = Tokenizer.from_file(str(TOKENIZER_JSON))
tok_json = json.loads(TOKENIZER_JSON.read_text(encoding="utf-8"))

# Report the effective unigram model config so we can align maxInputCharsPerSegment.
model_cfg = tok_json.get("model", {})
print("model.type =", model_cfg.get("type"))
for k in ("unk_id", "bos_id", "eos_id", "byte_fallback", "max_input_chars_per_word"):
    print(f"  {k} =", model_cfg.get(k, "<absent>"))

# Sampled strings covering: plain Chinese, mixed, English, numbers/symbols, boundary long CJK.
SAMPLES = [
    "你好，世界！",
    "今天天气怎么样？我想去公园散步。",
    "Prism is an Android AI assistant built with Jetpack Compose.",
    "昔涟这个角色做了哪些事情？",
    "12345 67890 +-*/ = .",
    "中文English混合Text示例",
    # 60-char CJK (no spaces) -> under 64, normal Viterbi
    "这是一段用于测试分词器在长无空格中文段落上的切分行为是否仍然保持子词合并而不是退化为逐字符切分的样例文本",
    # 88-char CJK (no spaces) -> segment length in (64, 100], must NOT degrade to per-char
    "这是一段用于锁定分词器在八十八个字符左右的长无空格中文段落上的切分行为是否正确保持子词合并而不会退化为逐字符切分以验证单段最大输入字符数上限与参考实现保持一致的样例句子文本内容",
]

rows = []
for s in SAMPLES:
    enc = tok.encode(s)
    ids = enc.ids
    tokens = enc.tokens
    rows.append((s, ids, tokens))

# Output as Kotlin source.
lines = []
lines.append("// AUTO-GENERATED by tools/gen_unigram_reference.py (HF tokenizers Rust %s)" % __import__("tokenizers").__version__)
lines.append("// Reference alignment golden data for UnigramTokenizerTest. Do NOT edit by hand.")
lines.append("// Regenerate: python tools/gen_unigram_reference.py")
lines.append("package io.prism.embedding")
lines.append("")
lines.append("/** Reference input_ids produced by HuggingFace `tokenizers` Rust Unigram. */")
lines.append("object UnigramTokenizerReference {")
lines.append("    /** (input text, expected input_ids list). */")
lines.append("    val SAMPLES: List<Pair<String, List<Int>>> = listOf(")
for s, ids, tokens in rows:
    esc = s.replace("\\", "\\\\").replace('"', '\\"')
    ids_str = ", ".join(str(x) for x in ids)
    lines.append(f'        "{esc}" to listOf({ids_str}),')
lines.append("    )")
lines.append("}")
out = "\n".join(lines) + "\n"
OUT_KT.write_text(out, encoding="utf-8")
print("Wrote", OUT_KT, f"({len(rows)} samples)")
for s, ids, tokens in rows:
    print(f"  [{len(s):3d} chars] -> {len(ids):3d} tokens | {s[:30]!r}")
